# Generated by Django 5.1.1 on 2024-09-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0002_allowance_user_deduction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='employee_net_pay',
        ),
        migrations.AddField(
            model_name='allowance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
